### ISSUE TITLE
Add backend listener for presence channel events to log user attendance

### ISSUE THREAD

**Issue by xaniuskarlhall** [laravel/reverb#185]
I am using this package to handle WebSocket connections and manage presence channels for a livestream feature in my application. I would like to log user attendance by tracking when users join or leave the livestream.
Is there a way to set up a listener or hook in the backend to capture the events when a user joins or leaves a presence channel? Ideally, I would like to be able to:

1. Detect when a user joins a presence channel and log their user ID, timestamp, and any other relevant information to track their attendance.
2. Detect when a user leaves a presence channel (either by explicitly leaving or due to disconnection) and log the corresponding information to mark the end of their attendance.
3. Store these attendance logs in a database or suitable storage mechanism for later analysis or reporting.

If there is a built-in way to achieve this using the Reverb package, please let me know. Otherwise, I would greatly appreciate any guidance or suggestions on how I can extend the package or implement a custom solution to log user attendance based on presence channel events.

**Comment by joedixon** [comment]
You could inspect the [MessageReceived](https://github.com/laravel/reverb/blob/78056b18086a5dcd0c50db8398e9be313e22624b/src/Events/MessageReceived.php#L8) event, which fires every time a user sends a message (such as requesting to join a channel). However, be wary that any action you carry out when this event is fired will block other messages flowing through the server from being processed.

**Comment by FojleRabbiRabib** [comment]
But, currently, there is no event similar to **pusher:unsubscribe**. How can disconnection events be handled?

**Comment by joedixon** [comment]
Reverb handles the unsubscribe event: https://github.com/laravel/reverb/blob/78056b18086a5dcd0c50db8398e9be313e22624b/src/Protocols/Pusher/EventHandler.php#L35

**Comment by Merraclius** [comment]
Hello @joedixon, I have a similar problem, I'm trying to use Reverb for detecting the "online" state of users. But what I see, is that Reverb handles unsubscribe events, which we can listen to through [MessageReceived](https://github.com/laravel/reverb/blob/f0cee423dce0ed8c8d65dbfdfc531b188627a50d/src/Events/MessageReceived.php#L8), but we can't listen to unsubscription event which is invoked after client disconnection https://github.com/laravel/reverb/blob/f0cee423dce0ed8c8d65dbfdfc531b188627a50d/src/Protocols/Pusher/Server.php#L76 
As a result, we can't detect when the user goes to "offline" status

**Comment by joedixon** [comment]
Thanks @Merraclius - can you provide a scenario where the unsubscription event which is invoked after client disconnection?

**Comment by Merraclius** [comment]
The most simple case. 
1. User open the page, we joining him to presence room. 
2. He close the tab/window Reverb catch the connection close event which fire unsubscribe event.
But this event only broadcasting the information about unsubscription to other clients (through broadcastInternally) but can't be catched inside our application

**Comment by joedixon** [comment]
Reverb will still dispatch the `MessageReceived` event, so you can hook into that?

**Comment by Merraclius** [comment]
No, because `MessageReceived` is dispatched only on receiving the message https://github.com/laravel/reverb/blob/f0cee423dce0ed8c8d65dbfdfc531b188627a50d/src/Protocols/Pusher/Server.php#L67, but in this case, the Reverb server doesn't receive any messages. It just detects that the connection is closing and no messages

**Comment by joedixon** [comment]
Gotcha - that's handled by the `close` method rather than on message receipt

https://github.com/laravel/reverb/blob/main/src/Protocols/Pusher/Server.php#L73-L85

I'll give this some thought, but I'm wary of adding more events due to the potential to block the event loop.

Thank you for the additional feedback 👍

**Comment by jakubforman** [comment]
It would be great to be able to catch and somehow react to connection termination directly on the server. For example, it would be possible to create a dashboard with real-time information about the status of devices  if they are online or offline (2 frontend applications in total - administration app and device app).

Maybe I'm wrong now, but I've been solving this very problem with event trapping and connection termination for about a week now. For example, if I have information about device changes under `company.{companyId}`, but I can detect connection closure on `device.{deviceId}` then I can send a message to company.{companyId} that the device is already offline or online or other data and notify administration app. Thus, a dashboard that lists all devices under company (1:N) would have only one open WS connection and would not need to implement N connections + Heatbeat + CRON to detect device disconnection.

I also tried `PresenceChannel`, but the current implementation is more for chat applications and cannot be used for anything else since it is built directly on user ID and this authorization. This greatly limits the possibilities, as for example there may be a 1:N binding where there are N devices under 1 company, and in the company I want to see which devices are currently online or offline.

If you have any ideas on how to achieve this without the "Heartbeat + CRON" of the app representing the device, that would be great.

**Comment by jakubforman** [comment]
I have created a fork and will prepare a PR when I add more event features, tests and I am sure it works fine. If you want to test the functionality of the event that is called when a connection is closed `Laravel\Reverb\Events\ChannelDisconnected;` https://github.com/jakubforman/reverb

**Comment by IggsGrey** [comment]
Since https://github.com/laravel/reverb/pull/206 was closed, are we looking at any other alternatives for logging user attendance (AKA detecting user online status)? besides monitoring events.

Could we, for instance, get the number of people in a channel?

**Comment by IggsGrey** [comment]
@joedixon

**Comment by sharaizk** [comment]
@joedixon, It would be highly beneficial to have an event listener for connection and disconnection events within Reverb. This enhancement would significantly broaden the utility of Reverb, like it can help in handling the statuses of the users 👍

**Comment by tobiasriemenschneider** [comment]
+1

**Comment by ReputableTomato** [comment]
Thought I'd post this here for anybody wanting to do this. You can use dependency injection to override the open and close method and implement your own logic.

CustomServer.php
`
use Laravel\Reverb\Protocols\Pusher\Server as BaseServer;

class CustomServer extends BaseServer
{
    public function open(Connection $connection): void
    {
        try {
            $this->verifyOrigin($connection);

            $connection->touch();

            $this->handler->handle($connection, 'pusher:connection_established');

            ConnectionOpened::dispatch($connection->id()); // dispatch your event here

            Log::info('Connection Established', $connection->id());
        } catch (Exception $e) {
            $this->error($connection, $e);
        }
    }

    public function close(Connection $connection): void
    {
        $this->channels
            ->for($connection->app())
            ->unsubscribeFromAll($connection);

        $connection->disconnect();

        ConnectionClosed::dispatch($connection->id()); // dispatch your event here

        Log::info('Connection Closed', $connection->id());
    }
}
`

It's frustrating that there is no movement on this. I would like to track a users open connections. I ended up having to do this so I can still use the default version of reverb without needing to edit it myself.

You can validate if a specific user is connecting by extracting the cookies from the connection buffer, and then going down the route of decrypting the cookie, getting the id, then matching it to a user id.

AppServiceProvider

`$this->app->bind(PusherServer::class, CustomPusherServer::class);`

Just to be clear. This is not a good solution, I do understand the concerns of potentially blocking the event loop, however I still think we should have the ability to listen into these events being fired.

**Comment by alparslanahmed** [comment]
+1

**Comment by bilbodog** [comment]
+1

**Comment by Hiiippo** [comment]
+1

**Comment by Firestorm7893** [comment]
+1

**Comment by GabrielBragaGit** [comment]
+1

**Comment by macsmitty** [comment]
+1

**Comment by dorianag** [comment]
+1

I require some sort of ability to run php code when the reverb detects connection close. On the backend, not through echo or anything like that. So I can fire and update my users online status when the connection is closed. This way, when there is only 1 user in the chat, there is no way whatsoever for me to fire php code to the updating when the connection is closed.

**Comment by msumdev** [comment]
> +1
> 
> I require some sort of ability to run php code when the reverb detects connection close. On the backend, not through echo or anything like that. So I can fire and update my users online status when the connection is closed. This way, when there is only 1 user in the chat, there is no way whatsoever for me to fire php code to the updating when the connection is closed.

Hey, I know the frustration. I commented a workaround above if you'd like to do this since it is pretty much the reason for me wanting to do it too.

@joedixon Would it be possible to have some feedback on this? If there are any plans to implement this?

**Comment by dorianag** [comment]
> > +1
> > I require some sort of ability to run php code when the reverb detects connection close. On the backend, not through echo or anything like that. So I can fire and update my users online status when the connection is closed. This way, when there is only 1 user in the chat, there is no way whatsoever for me to fire php code to the updating when the connection is closed.
> 
> Hey, I know the frustration. I commented a workaround above if you'd like to do this since it is pretty much the reason for me wanting to do it too.
> 
> [@joedixon](https://github.com/joedixon) Would it be possible to have some feedback on this? If there are any plans to implement this?

yeah I saw what you did, I will try it but I wanted to leave comment anyways to let creator know this is a real issue people are encountering with reverb

**Comment by carlosmera24** [comment]
Greetings, I appreciate the development of Reverb and everyone who has taken the time to comment and share their experiences and frustrations with not being able to detect user disconnection. @msumdev 's idea is very interesting and, so far, the only one I see as applicable—I will give it a try.

Currently, I am developing a Chat Room system where I need to identify connected users and remove those who disconnect in order to send FCM notifications or others. Since Reverb does not have an event that can be listened to for disconnection (pusher_internal:member_added, pusher_internal:member_removed) and that allows managing the registry—in my case, with Redis—I am leaving this comment to see if it would be possible, @joedixon, to add an event that lets us listen for connection and disconnection using pusher_internal:member_added, pusher_internal:member_removed.

Thank you in advance.

**Comment by kirkbushell** [comment]
This needs to be done. The idea that you don't want to block the event queue doesn't make sense, as you're already firing events around MessageReceived (which is a useful event to be able to hook into), so what's the issue with adding MemberAdded/Removed.etc. or any other ones? I think the idea that you want to stop developers from hurting themselves is a noble one, but it also harms those that know what they're doing, and is stark contrast to the general Laravel design which is one of not imposing its opinions on others.

To get around this, I implemented custom loggers, and then hooked into the logging. It's nasty, but it works. Ie. I rebound CliLogger and NullLogger to two new implementations, and then watched each log coming from Reverb, and acted on the events that I needed to listen to (that being the member_added and member_removed events when subscribing to a presence channel, and then I simply queued a job to do the database work I need.
