### ISSUE TITLE
Whisper events are being received multiple times when using the scaling function.

### ISSUE THREAD

**Issue by MarcelM1109** [laravel/reverb#270]
### Reverb Version

1.4.0

### Laravel Version

11.8.0

### PHP Version

8.2

### Description

When using the scaling function in Laravel Reverb, listenForWhisper events on the client side are triggered multiple times. When Client A sends a whisper event, the listenForWhisper event on Client B is triggered more than once, despite only one whisper event being expected.

### Steps To Reproduce

1. Enable the scaling function in Laravel Reverb.
2. Ensure both Client A and Client B join the same channel.
3. Have Client A send a whisper event in the channel.
4. Observe that Client B receives the whisper event multiple times instead of only once.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by MarcelM1109** [comment]
I just reproduced the issue again. Events are not received multiple times, but the sender of a client event does receive their own whisper when scaling is enabled. When scaling is disabled, a whisper is not received by the sender, so I assume this behavior is unintended.

**Comment by joedixon** [comment]
> I just reproduced the issue again. Events are not received multiple times, but the sender of a client event does receive their own whisper when scaling is enabled. When scaling is disabled, a whisper is not received by the sender, so I assume this behavior is unintended.

Looking into this a bit, I can see the issue. I'll address this soon.
